# Generated by Django 5.2.4 on 2025-07-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_saletransaction_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saletransaction',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
