# Generated by Django 5.2.4 on 2025-07-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_coupon_saleitem_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saletransaction',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saletransaction',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Credit', 'On Account'), ('Online', 'Online Payment'), ('Store Points', 'Store Points')], max_length=20),
        ),
    ]
