# Generated by Django 5.2.4 on 2025-07-15 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_category_options_alter_damagereport_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('stock_adjustment', 'Stock Adjustment'), ('damage_report', 'Damage Report'), ('stock_entry', 'Stock Entry'), ('stock_ledger', 'Ledger Update'), ('inventory_edit', 'Inventory Edit'), ('product_edit', 'Product Edit'), ('purchase_received', 'Purchase Received'), ('manual_override', 'Manual Override'), ('delete_action', 'Delete Action'), ('other', 'Other')], max_length=30)),
                ('related_id', models.PositiveIntegerField(blank=True, help_text='Optional ID of related model instance', null=True)),
                ('note', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.location')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
