# Generated by Django 5.2.4 on 2025-07-15 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loyalty.loyaltytier'),
        ),
    ]
