# Generated by Django 5.2.4 on 2025-07-08 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_address_customer_outstanding_balance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='loyaltytier',
            options={'ordering': ['-min_points']},
        ),
    ]
