# Generated by Django 5.2.4 on 2025-07-12 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_is_active'),
        ('loyalty', '0002_loyaltytier_alter_loyaltyprofile_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loyalty.loyaltytier'),
        ),
        migrations.DeleteModel(
            name='LoyaltyTier',
        ),
    ]
