# Generated by Django 5.2.4 on 2025-07-14 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customer_tier_delete_loyaltytier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditSale',
        ),
    ]
