# Generated by Django 5.2.4 on 2025-07-14 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
        ('customers', '0007_delete_creditsale'),
        ('sales', '0005_alter_saletransaction_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditledger',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Credit Ledger Entry', 'verbose_name_plural': 'Credit Ledger Entries'},
        ),
        migrations.AlterModelOptions(
            name='creditpayment',
            options={'ordering': ['-paid_on'], 'verbose_name': 'Credit Payment', 'verbose_name_plural': 'Credit Payments'},
        ),
        migrations.AlterModelOptions(
            name='creditsale',
            options={'ordering': ['-issued_on'], 'verbose_name': 'Credit Sale', 'verbose_name_plural': 'Credit Sales'},
        ),
        migrations.RenameField(
            model_name='creditsale',
            old_name='amount',
            new_name='credit_amount',
        ),
        migrations.RemoveField(
            model_name='creditsale',
            name='sale',
        ),
        migrations.AddField(
            model_name='creditsale',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='creditsale',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_sale', to='sales.saletransaction'),
        ),
        migrations.AlterField(
            model_name='creditledger',
            name='action',
            field=models.CharField(help_text="e.g., 'New Credit Sale', 'Partial Payment'", max_length=100),
        ),
        migrations.AlterField(
            model_name='creditsale',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_sales', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='creditsale',
            name='is_settled',
            field=models.BooleanField(default=False, help_text='Marked true once balance_due reaches zero'),
        ),
    ]
