# Generated by Django 5.2.4 on 2025-07-15 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0006_auditlog'),
        ('purchases', '0002_purchasereceipt_purchasereceiptitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_type', models.CharField(choices=[('received_damaged', 'Received Damaged'), ('in_store_damage', 'In-Store Damage'), ('expired', 'Expired'), ('theft', 'Theft'), ('spoilage', 'Spoilage')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('value_lost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reported_at', models.DateTimeField()),
                ('snapshot_created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('related_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.purchaseorder')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
    ]
