# Generated by Django 5.2.4 on 2025-07-18 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('inventory', '0008_remove_stockledger_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_orders', models.PositiveIntegerField()),
                ('total_qty_ordered', models.PositiveIntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'location')},
            },
        ),
    ]
