# Generated by Django 5.2.4 on 2025-07-12 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('min_points', models.PositiveIntegerField()),
                ('badge_color', models.CharField(default='gray', max_length=20)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            options={
                'ordering': ['-min_points'],
            },
        ),
        migrations.AlterField(
            model_name='loyaltyprofile',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loyalty.loyaltytier'),
        ),
    ]
