# Generated by Django 5.2.4 on 2025-07-17 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_stockledger_reason'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='locations',
            field=models.ManyToManyField(blank=True, help_text='Stores this user can access', related_name='user_profiles', to='inventory.location'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_profiles', to='inventory.location'),
        ),
    ]
